### ISSUE TITLE
Set headers exception

### ISSUE THREAD

**Issue by digitarald** [mozilla/platform-status#435]
Happens frequently on production

```
Error: Can't set headers after they are sent. at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
at ServerResponse.header (/app/node_modules/express/lib/response.js:718:10)
at /app/dist/app.js:27:9
at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix (/app/node_modules/express/lib/router/index.js:312:13)
at /app/node_modules/express/lib/router/index.js:280:7
at Function.process_params (/app/node_modules/express/lib/router/index.js:330:12)
at next (/app/node_modules/express/lib/router/index.js:271:10) at /app/dist/app.js:19:10
at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5) Context
```

**Comment by zalun** [comment]
After reading this - http://stackoverflow.com/questions/7042340/node-js-error-cant-set-headers-after-they-are-sent I think the problem is in redirect.
The only inconsistency I see in `app.js` is not returning `next()` in https://github.com/mozilla/platform-status/blob/master/app.js#L39
