### ISSUE TITLE
RangeNotSatisfiableError

### ISSUE THREAD

**Issue by digitarald** [mozilla/platform-status#436]
Happens a with low frequency on production.
```
RangeNotSatisfiableError: Range Not Satisfiable
at SendStream.error (/app/node_modules/send/index.js:245:31)
at SendStream.send (/app/node_modules/send/index.js:564:19)
at /app/node_modules/send/index.js:669:12 at FSReqWrap.oncomplete (fs.js:82:15) Context

```

**Comment by zalun** [comment]
Please provide link to the logs

**Comment by digitarald** [comment]
No public link. Click Logentries at https://dashboard.heroku.com/apps/platatus/resources

**Comment by digitarald** [comment]
Not seen again.
