### ISSUE TITLE
Improve CONTRIBUTING.md and setup instructions

### ISSUE THREAD

**Issue by stefanjudis** [mozilla/platform-status#510]
Hello Hello. 👋🏻

I just filed https://github.com/mozilla/platform-status/issues/509. And wanted to fix it myself and hand in a PR but unfortunately, I'm running into errors after cloning.

`npm start` and `npm run build` lead to the following:

```
[23:54:51] Failed to load external module @babel/register
[23:54:51] Failed to load external module babel-register
[23:54:51] Requiring external module babel-core/register
Building for development
[23:54:53] Using gulpfile ~/Projects/moz-platform-status/gulpfile.babel.js
[23:54:53] Starting 'build:routes'...
[23:54:53] Starting 'build:engines'...
[23:54:53] Starting 'build:root'...
[23:54:53] Starting 'build:tabzilla'...
[23:54:53] Starting 'build:status'...
[23:54:53] Starting 'build:css'...
[23:54:54] Starting 'build:js'...
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:1031:13)
    at _exceptionWithHostPort (util.js:1052:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1195:14)
```

Is Redis needed to run it locally? 

Thanks. :)

**Comment by marco-c** [comment]
Yes, Redis is required. We should indeed document it in CONTRIBUTING.md.
